//Testing the "Add Doctor" endpoint
POST http://localhost:8080/doctors
Content-Type: application/json

{
    "id": "1",
    "name": "Strange",
    "role": "DOCTOR"
}

###

//Testing the "Get All Doctors" endpoint 
GET http://localhost:8080/doctors

###

//Testing the "Get Doctor by ID" endpoint
GET http://localhost:8080/doctors/1

###

//Testing the "Add Patient" endpoint
POST http://localhost:8080/patients
Content-Type: application/json

{
    "id": "1",
    "name": "Mr. Z",
    "role": "PATIENT"
}

###

//Testing the "Get All Patients" endpoint 
GET http://localhost:8080/patients

###

//Testing the "Get Patient by ID" endpoint
GET http://localhost:8080/patients/1

###

//Testing the "Login" endpoint
POST http://localhost:8080/login
Content-Type: application/json

{
    "name":"",
    "password":""
}

###

//Testing the "Appointment Booking" endpoint
POST http://localhost:8080/appointments/book
Content-Type: application/json

{
    "time": "2",
    "id": 3,
    "doctorid": "1",
    "patientid": "1",
    "duration": "25",
    "timestart": "1",
    "timeend": "2"
}