//Testing the "Add Doctor" endpoint
POST http://localhost:8080/doctors
Content-Type: application/json

{
    "id": "1",
    "name": "Strange",
    "role": "DOCTOR"
}

###

//Testing the "Get All Doctors" endpoint 
GET http://localhost:8080/doctors

###

//Testing the "Get Doctor by ID" endpoint
GET http://localhost:8080/doctors/1

###

//Testing the "Add Patient" endpoint
POST http://localhost:8080/patients
Content-Type: application/json

{
    "id": "3",
    "name": "Mr. H",
    "role": "PATIENT"
}

###

//Testing the "Get All Patients" endpoint 
GET http://localhost:8080/patients

###

//Testing the "Get Patient by ID" endpoint
GET http://localhost:8080/patients/1

###

//Testing the "Login" endpoint
POST http://localhost:8080/login
Content-Type: application/json

{
    "Email":"tester@email.com",
    "Password":"testpass"
}
###

//Testing the "Appointment Booking" endpoint
POST http://localhost:8080/appointments/book
Content-Type: application/json

{
    "time": "2",
    "id": 2,
    "doctorid": "1",
    "patientid": "3",
    "duration": 30,
    "timestart": "1",
    "timeend": "2"
}

###
//Testing registration endpoint

POST http://localhost:8080/register
Content-Type: application/json

{
"ID":"1",
"Name": "Tester",
"Email":"tester@email.com",
"Password": "testpass",
"Role": "PATIENT"

}

###

POST http://localhost:8080/testuseradd
Content-Type: application/json

{
"ID":"1",
"Name": "Tester",
"Email":"tester@email.com",
"Password": "$2a$14$nX6.hzvPp/qqQbIc.WG5Lej1nSKRSi9hrA01m/8Mrd24bDAxBheM6",
"Role": "PATIENT"

}

###
PATCH http://localhost:8080/book/1/8:30

###
GET http://localhost:8080/appointments/view/all

###
GET http://localhost:8080/appointments/view/23

###
GET http://localhost:8080/appointments/view/patient/3

###
GET http://localhost:8080/appointments/view/max